# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-23 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('source', models.CharField(max_length=225, null=True)),
                ('cancer_type', models.CharField(max_length=225, null=True)),
                ('dataset_description', models.CharField(max_length=225, null=True)),
                ('normal_n', models.IntegerField(null=True)),
                ('tumor_n', models.IntegerField(null=True)),
                ('build', models.CharField(max_length=225, null=True)),
                ('read_length', models.IntegerField(null=True)),
                ('sequencing_strategy', models.CharField(max_length=225, null=True)),
            ],
        ),
    ]
