# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snorna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clinical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('sample_id', models.CharField(max_length=225, null=True)),
                ('time', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('subtype', models.CharField(max_length=225, null=True)),
                ('stage', models.CharField(max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='genomic_analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('sample_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225, null=True)),
                ('gene_expression', models.FloatField()),
                ('mirna_expression', models.FloatField()),
                ('cna', models.FloatField()),
                ('protein_expression', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='snorna_expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id_expression', models.CharField(max_length=225, null=True)),
                ('sample_id', models.CharField(max_length=225, null=True)),
                ('snorna_expression', models.FloatField()),
            ],
        ),
    ]
