# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snorna', '0003_auto_20170223_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomic_analysis',
            name='cna',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='genomic_analysis',
            name='gene_expression',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='genomic_analysis',
            name='mirna_expression',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='genomic_analysis',
            name='protein_expression',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='snorna_expression',
            name='snorna_expression',
            field=models.FloatField(null=True),
        ),
    ]
