# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snorna', '0004_auto_20170223_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='clinical_subtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('subtype', models.CharField(max_length=225, null=True)),
                ('state', models.CharField(max_length=225, null=True)),
                ('n', models.IntegerField(null=True)),
            ],
        ),
    ]
