# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snorna', '0005_clinical_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='snorna_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('chrom', models.CharField(max_length=45, null=True)),
                ('strand', models.CharField(max_length=45, null=True)),
                ('start', models.IntegerField(null=True)),
                ('end', models.IntegerField(null=True)),
                ('symbold', models.CharField(max_length=45, null=True)),
                ('type', models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
