# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snorna', '0007_cnv_methylation_mrna_expression'),
    ]

    operations = [
        migrations.CreateModel(
            name='mrna_expression_ACC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225, null=True)),
                ('host', models.IntegerField(null=True)),
                ('spearman_corr', models.FloatField(null=True)),
                ('p_value', models.FloatField(null=True)),
                ('fdr', models.FloatField(null=True)),
                ('sample_id', models.CharField(max_length=225, null=True)),
                ('rna_expression', models.FloatField(null=True)),
            ],
        ),
    ]
