# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snorna', '0012_snorna_expression_acc_snorna_expression_blca_snorna_expression_brca_snorna_expression_cesc_snorna_ex'),
    ]

    operations = [
        migrations.CreateModel(
            name='gene_symbol_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
    ]
