# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snorna', '0013_gene_symbol_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='gene_snorna_pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
    ]
