# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snorna', '0014_gene_snorna_pair'),
    ]

    operations = [
        migrations.CreateModel(
            name='gene_snorna_pair_ACC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_BLCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_BRCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_CESC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_CHOL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_COAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_DLBC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_ESCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_HNSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_KICH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_KIRC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_KIRP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_LGG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_LIHC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_LUAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_LUSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_MESO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_OV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_PAAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_PCPG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_PRAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_READ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_SARC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_SKCM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_STAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_TGCT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_THCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_THYM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_UCEC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_UCS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gene_snorna_pair_UVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snorna', models.CharField(max_length=225, null=True)),
                ('dataset_id', models.CharField(max_length=225, null=True)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
    ]
