# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-21 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snorna', '0015_gene_snorna_pair_acc_gene_snorna_pair_blca_gene_snorna_pair_brca_gene_snorna_pair_cesc_gene_snorna_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='rppa_name_symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.CharField(max_length=225)),
                ('gene_symbol', models.CharField(max_length=225)),
            ],
        ),
    ]
